version: "3"
services:
  metricbeat:
    build:
      context: .
      dockerfile: dockerfile.metricbeat
    entrypoint: ["sh", "-c", "cd /ansible_metricbeat; ansible-playbook local_playbook.yml;sleep 2073600"]
    volumes:
      - .:/ansible_metricbeat
  kibana:
    image: kibana:7.8.1
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:7.8.1
    env_file:
      - elasticsearch.env
    ports:
      - 9200:9200
