---

- hosts: localhost
  tasks:
    - name: setup metricbeat plugin
      ansible.builtin.command: /usr/bin/ansible-galaxy install elastic.beats,v7.13.1
      register: myag
    - debug: msg="{{myag.stdout}}"
    - debug: msg="{{myag.stderr}}"
    - name: install metricbeat plugin
      include_role: 
        name: elastic.beats
      vars: 
        beats: 7.13.1
        beat: metricbeat
        output_conf : 
          elasticsearch:
            hosts: "elasticsearch:9200"
        beat_conf:
          metricbeat.modules:
            - module: system
              metricsets:
                - filesystem     # File system usage for each mountpoint
              enabled: true
              period: 10s
              processes: ['.*']
